Repository Sheweny/framework, pull requests merged in 2021-08, with the labels that each got.

#59 Js doc
  src/client/Client.ts
  src/interfaces/Client.ts
  src/interfaces/Command.ts
  src/interfaces/Handlers.ts
  src/managers/ButtonsManager.ts
  src/managers/CommandsManager.ts
  src/managers/EventsManager.ts
  src/managers/InhibitorsManager.ts
  src/managers/SelectMenusManager.ts
  src/structures/BaseStructure.ts
  src/structures/Button.ts
  src/structures/Command.ts
  src/structures/Event.ts
  src/structures/Inhibitor.ts
  src/structures/SelectMenu.ts
  typings/index.d.ts
Labels: documentation

#64 Fixes
  src/client/Client.ts
  src/managers/CommandsManager.ts
  typings/index.d.ts
Labels: bug, enhancement

#69 Fixs
  package.json
  src/client/Client.ts
  src/errors/ShewenyError.ts
  src/events/interactionCommandCreate.ts
  src/interfaces/Client.ts
  typings/index.d.ts
Labels: bug
